# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: required
language: python
group: deprecated-2017Q4
os: linux

git:
  depth: 20

# blas and openblas from APT is much slower than "sudo apt-get -qq install"
#addons:
#  apt:
#    packages:
#    - gcc
#    - g++
#    - gfortran
#    - libblas-dev
#    - curl
#    - cmake

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
# 3.7 not available in group deprecated-2017Q4
#  - 3.7

#virtualenv:  affect python 3.5 3.6?
#    system_site_packages: true

before_install:
  - sudo apt-get -qq install gcc libblas-dev cmake curl
  - pip install numpy scipy h5py nose nose-exclude nose-timer

install:
  # openblas from numpy may be slightly faster than the default libblas library
  #- cd $TRAVIS_BUILD_DIR/pyscf/lib &&
  #  ln -s `python -c "import os, numpy; print(os.path.dirname(numpy.__file__))"`/.libs/lib* ./ &&
  #  blaslib=`basename libopenblas* .so | cut -c 4-` &&
  #  echo 'set(BLAS_LIBRARIES "-L${PROJECT_SOURCE_DIR} -l'${blaslib}'")' > cmake.arch.inc
  - cd $TRAVIS_BUILD_DIR/pyscf/lib &&
    curl http://www.sunqm.net/pyscf/files/bin/pyscf-1.6-deps.tar.gz | tar xzf -
  - cd $TRAVIS_BUILD_DIR/pyscf/lib &&
    mkdir build &&
    cd build &&
    cmake -DBUILD_XCFUN=OFF .. &&
    make &&
    cd ../..

before_script:
  - rm $TRAVIS_BUILD_DIR/pyscf/pbc/tools/pyscf_ase.py

script:
  - cd $TRAVIS_BUILD_DIR/pyscf &&
    echo 'pbc_tools_pbc_fft_engine = "NUMPY"' > pyscf_config.py
  - OMP_NUM_THREADS=1 PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH PYSCF_CONFIG_FILE=$(pwd)/pyscf_config.py
    nosetests -v
    -e geomopt -e dmrgscf -e fciqmcscf -e icmpspt -e examples -e nao
    -e cornell_shci
    -e test_bz
    -e h2o_vdz
    -e test_mc2step_4o4e
    -e test_ks_noimport
    -e test_jk_single_kpt
    -e test_jk_hermi0
    -e test_j_kpts
    -e test_k_kpts
    -e high_cost
    -e skip
    -e call_in_background
    -e libxc_cam_beta_bug
    -I test_kuccsd_supercell_vs_kpts\.py
    -I test_kccsd_ghf\.py
    -I test_h_.*\.py
