name: Build

# Only trigger, when the build workflow succeeded
#on:
#  workflow_run:
#    workflows: ["Publish to PyPI"]
#    types:
#      - completed
on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Make sure tags are fetched so we can get a version.
      - run: |
          git fetch --prune --unshallow --tags
      - name: Build wheels
        if: runner.os == 'Linux'
        uses: pypa/cibuildwheel@2.6.0
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BEFORE_ALL: yum -y update && yum -y install blas-devel cmake curl

      - name: Build wheels
        if: runner.os != 'Linux'
        uses: pypa/cibuildwheel@2.6.0
        env:
          CIBW_ARCHS_MACOS: arm64

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

#  # Upload wheels to PyPi
#  upload_wheels:
#    needs: build_wheels
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download built wheels
#        uses: actions/download-artifact@v2
#        with:
#          name: wheels
#          path: wheelhouse
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -U twine 
#      - name: Build and publish
#        env:
#          # Remove AA for production...
#          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#
#        run: |
#          twine upload wheelhouse/*
