name: Lint

on: [push, pull_request]

jobs:
  flake:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install "flake8>=3.7.0"
      - name: Static analysis
        run: flake8 --config .flake8 pyscf

#      - name: Static analysis
#        uses: suo/flake8-github-action@releases/v1
#        with:
#          checkName: 'flake'   # NOTE: this needs to be the same as the job name
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: flake8 --config .flake8 pyscf
